#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dry="0"

if [[ -z "${XDG_CONFIG_HOME:-}" ]]; then
    echo "XDG_CONFIG_HOME is not set. Defaulting to \$HOME/.config"
    XDG_CONFIG_HOME="$HOME/.config"
fi

while [[ $# -gt 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi
    "$@"
}

sync_dir() {
    src="$1"
    dest="$2"
    log "Syncing directory: $src -> $dest"
    execute mkdir -p "$dest"
    execute rsync -a --delete --force "$src"/ "$dest"/
}

sync_file() {
    src="$1"
    dest="$2"
    log "Syncing file: $src -> $dest"
    execute cp "$src" "$dest"
}

log "--- dev-env ---"

cd "$script_dir"

sync_dir ".config" "$XDG_CONFIG_HOME"
sync_dir ".gnupg" "$HOME/.gnupg"
sync_dir ".local/bin" "$HOME/.local/bin"
sync_file ".zshrc" "$HOME/.zshrc"
sync_file ".zprofile" "$HOME/.zprofile"
