#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dry="0"

if [[ -z "${XDG_CONFIG_HOME:-}" ]]; then
    echo "XDG_CONFIG_HOME is not set. Defaulting to \$HOME/.config"
    XDG_CONFIG_HOME="$HOME/.config"
fi

while [[ $# -gt 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi
    "$@"
}

sync_dir() {
    src="$1"
    dest="$2"
    log "Syncing directory: $src -> $dest"
    execute mkdir -p "$dest"
    execute rsync -a --delete --force "$src"/ "$dest"/
}

sync_file() {
    src="$1"
    dest="$2"
    log "Syncing file: $src -> $dest"
    execute cp "$src" "$dest"
}

gpg_setup() {
    log "Setting up GPG..."
    execute mkdir -p "$HOME/.gnupg"
    execute chmod 700 "$HOME/.gnupg"
    execute cp .gnupg/gpg-agent.conf "$HOME/.gnupg/gpg-agent.conf"
    execute cp .gnupg/gpg.conf "$HOME/.gnupg/gpg.conf"
    execute cp .gnupg/scdaemon.conf "$HOME/.gnupg/scdaemon.conf"
    log "Importing public key from GitHub..."
    if [[ $dry == "0" ]]; then
        curl -sf https://github.com/gabrielsten.gpg | gpg --import
    else
        log "[DRY_RUN]: curl https://github.com/gabrielsten.gpg | gpg --import"
    fi
}

log "--- dev-env ---"

cd "$script_dir"

sync_dir ".config" "$XDG_CONFIG_HOME"
gpg_setup
sync_dir ".local/bin" "$HOME/.local/bin"
execute chmod +x "$HOME/.local/bin/tmux-sessionizer"
sync_file ".zshrc" "$HOME/.zshrc"
sync_file ".zprofile" "$HOME/.zprofile"
sync_file ".gitconfig" "$HOME/.gitconfig"
